// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2X4dwQs5qX8rU5bJGPSvfJvm4yDEWCCo',
    appId: '1:376279425097:web:fcacc20e7a2c6618b91f98',
    messagingSenderId: '376279425097',
    projectId: 'barcodefee-f4c9d',
    authDomain: 'barcodefee-f4c9d.firebaseapp.com',
    databaseURL: 'https://barcodefee-f4c9d-default-rtdb.firebaseio.com',
    storageBucket: 'barcodefee-f4c9d.appspot.com',
    measurementId: 'G-18RRQJHK3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqJLcdMTR4eQFyf5grcMPKHtZ_H07T8w',
    appId: '1:376279425097:android:a052b503be390a50b91f98',
    messagingSenderId: '376279425097',
    projectId: 'barcodefee-f4c9d',
    databaseURL: 'https://barcodefee-f4c9d-default-rtdb.firebaseio.com',
    storageBucket: 'barcodefee-f4c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHZml9APNA8DThWMzjkeBqdhOY7mSpOE',
    appId: '1:376279425097:ios:42ee46335d0755a5b91f98',
    messagingSenderId: '376279425097',
    projectId: 'barcodefee-f4c9d',
    databaseURL: 'https://barcodefee-f4c9d-default-rtdb.firebaseio.com',
    storageBucket: 'barcodefee-f4c9d.appspot.com',
    iosClientId: '376279425097-38drncqqq4tfah61dk3qklj54aj71v19.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTrialV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHZml9APNA8DThWMzjkeBqdhOY7mSpOE',
    appId: '1:376279425097:ios:42ee46335d0755a5b91f98',
    messagingSenderId: '376279425097',
    projectId: 'barcodefee-f4c9d',
    databaseURL: 'https://barcodefee-f4c9d-default-rtdb.firebaseio.com',
    storageBucket: 'barcodefee-f4c9d.appspot.com',
    iosClientId: '376279425097-38drncqqq4tfah61dk3qklj54aj71v19.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTrialV1',
  );
}
